### ISSUE TITLE
Table name override does not work for find operations

### ISSUE THREAD

**Issue by jehanzebqayyum** [boostchicken/spring-data-dynamodb#107]
## Expected Behavior

Table name override does not work for find by id and i get resource not found exception from dynamodb

` DynamoDBMapperConfig
            .Builder()
            .withTableNameOverride(tableNameOverrider)
            .withTypeConverterFactory(DynamoDBTypeConverterFactory.standard())
            .build()`

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications
  
  - Spring Data DynamoDB Version: 
  - Spring Data Version:
  - AWS SDK Version:
  - Java Version: 
  - Platform Details: 

All those information are logged by `org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory` on `INFO` level on startup.
Or use `java -version` and `mvn dependency:tree | grep -E 'spring|aws'` to provide those version numbers.

**Comment by thanosa75** [comment]
@boostchicken this is confirmed

 Spring Data DynamoDB Version: 5.2.5 (2.2)
 Spring Data Version:          2.3.4.RELEASE
 AWS SDK Version:              1.11.874
 Java Version:                 11.0.6 - OpenJDK 64-Bit Server VM 11.0.6+10-post-Debian-1bpo91
 Platform Details:             Linux 4.14.177-139.253.amzn2.x86_64

**Comment by jehanzebqayyum** [comment]
@thanosa75 i forgot to mention this workaround worked for me. i think its also mentioned somewhere else also i.e. use `dynamoDBMapperConfigRef` to refer to the `dynamoDBMapperConfig` bean:

```
@Configuration
@EnableDynamoDBRepositories(dynamoDBMapperConfigRef = "dynamoDBMapperConfig")
class DynamoDbConfiguration() {

    @Bean("dynamoDBMapperConfig")
    fun dynamoDBMapperConfig(tableNameOverrider: DynamoDBMapperConfig.TableNameOverride)...
```
