### ISSUE TITLE
is it possible to determine the dynamodb region in runtime

### ISSUE THREAD

**Issue by xinatcg** [boostchicken/spring-data-dynamodb#46]
is it possible to determine the DynamoDB region in runtime?

The requirement is:
We have multiple type environment servers such as dev,QA, etc. and different servers connect to different regions of DynamoDB. but we want to make a single back office to manage all the data on different regions of DynamoDB. So we need to determine the region in runtime, for example, we can switch region by invoking an API.

If use the AWS SDK, it seems like we need to build different `AmazonDynamoDBClientBuilder`, but is it possible by using this Spring-data-dynamodb achieve like that?

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications
  
  - Spring Data DynamoDB Version: 
  - Spring Data Version:
  - AWS SDK Version:
  - Java Version: 
  - Platform Details: 

All those information are logged by `org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactory` on `INFO` level on startup.
Or use `java -version` and `mvn dependency:tree | grep -E 'spring|aws'` to provide those version numbers.

**Comment by boostchicken** [comment]
```
    @Bean
    public AmazonDynamoDB amazonDynamoDB()
    {
        Region region = Regions.getCurrentRegion();
        if(region == null) {
            region = RegionUtils.getRegion("us-east-1");
        }
        return AmazonDynamoDBClientBuilder.standard().withRegion(region.getName()).build();
    }
```

**Comment by xinatcg** [comment]
1

**Comment by xinatcg** [comment]
Hi, thanks for you response. but I think this solution still cannot change the region in runtime

I try to use the spring dynamic register / destroy the bean to change the region at runtime. but find a strange result. even the inject been has been updated to new region, but the repository still query data from region which in initial config bean.

```kotlin
fun switch(dynamoDBTarget: DynamoDBTarget) {
        val beanFactory = (appContext as ConfigurableApplicationContext).beanFactory as DefaultListableBeanFactory
        beanFactory.destroySingleton("amazonDynamoDB")
//        beanFactory.destroySingleton("dynamoDBMapperConfig")
//        beanFactory.destroySingleton("dynamoDBMapper")
        beanFactory.destroySingleton("dynamoDB-DynamoDBMapper")
        val bean = AmazonDynamoDBClientBuilder.standard()
                .withCredentials(amazonAwsCredentialsProvider())
                .withRegion(Regions.EU_WEST_1)
                .build()
        val conf = dynamoDBMapperConfig()
        val mapper = dynamoDBMapper(bean, conf)
        beanFactory.registerSingleton("amazonDynamoDB", bean)
//        beanFactory.registerSingleton("dynamoDBMapperConfig", conf)
//        beanFactory.registerSingleton("dynamoDBMapper", mapper)
//        beanFactory.registerSingleton("dynamoDB-DynamoDBMapper", mapper)
        beanFactory
    }

```


![image](https://user-images.githubusercontent.com/55399567/86213922-5bdb8380-bb72-11ea-895e-5154f4f21914.png)

**Comment by xinatcg** [comment]
![image](https://user-images.githubusercontent.com/55399567/86214204-c1c80b00-bb72-11ea-8ade-9ac430d9c7d8.png)

**Comment by xinatcg** [comment]
![image](https://user-images.githubusercontent.com/55399567/86214343-f89e2100-bb72-11ea-89e8-90d0209251f2.png)

**Comment by xinatcg** [comment]
I expect to get data from the `eu-west-2` before the switch function and get data from `eu-west-1` after the switch. is it possible? @boostchicken

**Comment by boostchicken** [comment]
@xinatcg I see what you are saying here.  I think you are going to have to reconstruct a whole new set of objects, including your repositories. dynamodbclient, and dynamodbmapper.  Everything is going to have to re-wired and I believe the DynamoDBOperations object is the most critical.  If that does not get an updated client it wont matter.
