### ISSUE TITLE
DynamoDBIndexHashKey bug with TableNamePrefix

### ISSUE THREAD

**Issue by 291277058** [boostchicken/spring-data-dynamodb#47]
## Expected Behavior
set DynamoDBMapperConfig with the TableNamePrefix,the find result should come from table "TableNamePrefix+tablename"

## Actual Behavior
the result come from table "tablename"

## Steps to Reproduce the Problem
set DynamoDBMapperConfig
`@Primary
    @Bean
    public DynamoDBMapperConfig dynamoDBMapperConfig() {
        return DynamoDBMapperConfig.builder()
                .withTableNameOverride(
                        DynamoDBMapperConfig.TableNameOverride.withTableNamePrefix(tableNamePrefix)
                ).build();
    }`
add DynamoDBIndexHashKey
`@DynamoDBIndexHashKey(globalSecondaryIndexName = "username-index")`

use Repository do the find method
## Specifications
  
  - Spring Data DynamoDB Version: 5.2.5
  - Spring Data Version:Moore-RELEASE
  - AWS SDK Version:2.7.7
  - Java Version: 8
  - Platform Details: linux

**Comment by boostchicken** [comment]
Hey @291277058 , can you post a more detailed error / stack trace?  I am not sure exactly what is erroring here.  Is it doing a Scan when it should be doing a query?

**Comment by 291277058** [comment]
Hi, it happens when i do a query like `UserInfo byUserId = userInfoRepository.findByUsername(s);` If i add index on the username ,the problem happends.I read the source code , the problem at `DynamoDBEntityMetadataSupport` line 78, maybe should use method `DynamoDBTemplate.getOverriddenTableName`. 
And thanks for you work, have a nice day.

**Comment by 291277058** [comment]
I create a PR to fix this, if you can public this version soon as possible it will be very helpfull to me. @boostchicken

**Comment by 291277058** [comment]
DynamoDBMapperConfig work like the fellow example

`
@EnableDynamoDBRepositories(dynamoDBMapperConfigRef = "dynamoDBMapperConfig",
        includeFilters = {@ComponentScan.Filter(type = FilterType.ANNOTATION)})
`

`
    @Primary
    @Bean
    public DynamoDBMapperConfig dynamoDBMapperConfig() {
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.DEFAULT;
        return new DynamoDBMapperConfig.Builder()
                .withTableNameOverride(DynamoDBMapperConfig.TableNameOverride.withTableNamePrefix(tableNamePrefix))
                .withConversionSchema(mapperConfig.getConversionSchema())
                .withBatchLoadRetryStrategy(mapperConfig.getBatchLoadRetryStrategy())
                .withConsistentReads(mapperConfig.getConsistentReads())
                .withBatchWriteRetryStrategy(mapperConfig.getBatchWriteRetryStrategy())
                .withObjectTableNameResolver(mapperConfig.getObjectTableNameResolver())
                .withPaginationLoadingStrategy(mapperConfig.getPaginationLoadingStrategy())
                .withRequestMetricCollector(mapperConfig.getRequestMetricCollector())
                .withSaveBehavior(mapperConfig.getSaveBehavior())
                .withTableNameResolver(mapperConfig.getTableNameResolver())
                .withTypeConverterFactory(mapperConfig.getTypeConverterFactory())
                .build();
    }
`

**Comment by boostchicken** [comment]
@291277058 I put some comments on your PR after I understand your change a bit better I can roll out a snapshot

**Comment by pettyalex** [comment]
@boostchicken This is affecting my group too, we'd love a quick snapshot so we don't have to hack around it.
