### ISSUE TITLE
How to generate audit log for dynamodb record actions (get, update, delete)?

### ISSUE THREAD

**Issue by atigm** [boostchicken/spring-data-dynamodb#93]
How to integrate an Audit API like spring envers or others ?

Thank you

**Comment by boostchicken** [comment]
https://github.com/boostchicken/spring-data-dynamodb/tree/develop/src/main/java/org/socialsignin/spring/data/dynamodb/mapping/event

See those packages.  T here is a page on it in the Wiki of derjusts repo as well I believe
